version: 3

vars:
  GOALC_BIN_RELEASE_DIR: './build/Release/bin/goalc'
  GK_BIN_RELEASE_DIR: './build/Release/bin/game'
  DECOMP_BIN_RELEASE_DIR: './build/Release/bin/decompiler'
  MEMDUMP_BIN_RELEASE_DIR: './build/Release/bin/tools'
  TYPESEARCH_BIN_RELEASE_DIR: './build/Release/bin/tools'
  OFFLINETEST_BIN_RELEASE_DIR: './build/Release/bin'
  GOALCTEST_BIN_RELEASE_DIR: './build/Release/bin'
  EXE_FILE_EXTENSION: ''
