name: 🏭 Cut Mod Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  cut_release:
    name: "Cut Release"
    uses: OpenGOAL-Mods/legacy-mod-bundling-tools/.github/workflows/mod-bundler.yml@v1
    with:
      semverBump: ${{ inputs.bump }}
      metadataName: "Jak the CHICKEN"
      metadataDescription: "Adds over 18 levels and 900+ collectibles to the game and new powerups and adventures! Note: currently it is disguised as a fart mod. It is not."
      metadataSupportedGames: "jak1"
      metadataAuthors: "zed"
      metadataTags: "challenge,speedrunning,gameplay-mod"
      metadataWebsiteUrl: "https://github.com/my-opengoal-mods/OG-Jak-The-Chicken-Reborn/blob/main/README.md"
      skipMacOS: true
      skipLinux: true
      toolingBinaryDir: "out/build/Release/bin"
      gameAssetsDir: "game/assets"
      copyEntireBinaryDir: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
